#!/bin/bash
set -e

chmod 600 /etc/shibboleth/*.pem
chown _shibd:_shibd /etc/shibboleth/*.pem /run/shibboleth -R

if [ "${SHIB_IDP_ENTITY_ID}" != "" ];then
	SHIB_SSO_ATTRS="entityID=\"${SHIB_IDP_ENTITY_ID}\""
elif [ "${SHIB_IDP_DISCOVERY_URL}" != "" ];then
	SHIB_SSO_ATTRS="discoveryProtocol=\"SAMLDS\" discoveryURL=\"${SHIB_IDP_DISCOVERY_URL}\""
else
	echo "you have either to provide the SHIB_IDP_DISCOVERY_URL or the SHIB_IDP_ENTITY_ID
environment variable in order to correctly set up shibboleth. exiting ...";
	exit 1;
fi

METADATA_PROVIDER_DFN='
        <MetadataProvider type="XML" uri="https://www.aai.dfn.de/fileadmin/metadata/DFN-AAI-Test-metadata.xml" backingFilePath="federation-metadata.xml" reloadInterval="7200">
            <MetadataFilter type="RequireValidUntil" maxValidityInterval="2419200"/>
            <MetadataFilter type="Signature" certificate="/etc/shibboleth/dfn-aai-cert.pem"/>
        </MetadataProvider>
'

METADATA_PROVIDER_LOCAL='
        <MetadataProvider type="XML" file="partner-metadata.xml"/>
'

if [ "${SHIB_ATTRIBUTE_MAP}" != "" ]; then
  IFS=',' read -ra attrlist <<< "${SHIB_ATTRIBUTE_MAP}";
  for attr in "${attrlist[@]}" ;do
    ATTRIBUTE_XML="${ATTRIBUTE_XML}
  <Attribute name=\"${attr%%=*}\" id=\"${attr#*=}\" />\n"
  done
  sed -e 's!</Attributes>!!' -i /etc/shibboleth/attribute-map.xml
  echo -e "${ATTRIBUTE_XML}\n</Attributes>" >>/etc/shibboleth/attribute-map.xml
fi

cat >/etc/shibboleth/shibboleth2.xml <<EOF
<SPConfig xmlns="urn:mace:shibboleth:2.0:native:sp:config"
    xmlns:conf="urn:mace:shibboleth:2.0:native:sp:config"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
    xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"
    logger="console.logger"
    clockSkew="180">

    <ApplicationDefaults entityID="${SHIB_SP_ENTITY_ID}" REMOTE_USER="eppn persistent-id targeted-id">

        <Sessions lifetime="28800" timeout="3600" relayState="ss:mem" checkAddress="false" handlerSSL="true" cookieProps="; path=/; secure; HttpOnly" handlerURL="${SHIB_HANDLER_URL}">
            <SSO ${SHIB_SSO_ATTRS}>
              SAML2 SAML1
            </SSO>
            <Logout>SAML2 Local</Logout>
            <Handler type="MetadataGenerator" Location="/Metadata" signing="false"/>
            <Handler type="Status" Location="/Status" acl="${SHIB_STATUS_ACL} 127.0.0.1 ::1"/>
            <Handler type="Session" Location="/Session" showAttributeValues="true"/>
            <Handler type="DiscoveryFeed" Location="/DiscoFeed"/>
        </Sessions>

        <Errors supportContact="root@localhost"
            helpLocation="/about.html"
            styleSheet="/shibboleth-sp/main.css"/>

        ${METADATA_PROVIDER_DFN}

        <AttributeExtractor type="XML" validate="true" reloadChanges="false" path="attribute-map.xml"/>
        <AttributeResolver type="Query" subjectMatch="true"/>
        <AttributeFilter type="XML" validate="true" path="attribute-policy.xml"/>
        <CredentialResolver type="File" key="sp-key.pem" certificate="sp-cert.pem"/>
    </ApplicationDefaults>
    <SecurityPolicyProvider type="XML" validate="true" path="security-policy.xml"/>
    <ProtocolProvider type="XML" validate="true" reloadChanges="false" path="protocols.xml"/>
</SPConfig>
EOF

cat >/etc/shibboleth/metadata.xml <<EOF
<!--
This is example metadata only. Do *NOT* supply it as is without review,
and do *NOT* provide it in real time to your partners.
 -->
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" ID="_f46fa7b46e8469845f8cb9c328321bbeba0308d2" entityID="${SHIB_SP_ENTITY_ID}">

  <md:Extensions xmlns:alg="urn:oasis:names:tc:SAML:metadata:algsupport">
    <alg:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/>
    <alg:DigestMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#sha384"/>
    <alg:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
    <alg:DigestMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#sha224"/>
    <alg:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha224"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha512"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha384"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2009/xmldsig11#dsa-sha256"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2000/09/xmldsig#dsa-sha1"/>
  </md:Extensions>

  <md:SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol">
    <md:Extensions>
      <init:RequestInitiator xmlns:init="urn:oasis:names:tc:SAML:profiles:SSO:request-init" Binding="urn:oasis:names:tc:SAML:profiles:SSO:request-init" Location="${SHIB_HOSTNAME}${SHIB_HANDLER_URL}/Login"/>
      <idpdisc:DiscoveryResponse xmlns:idpdisc="urn:oasis:names:tc:SAML:profiles:SSO:idp-discovery-protocol" Binding="urn:oasis:names:tc:SAML:profiles:SSO:idp-discovery-protocol" Location="${SHIB_HOSTNAME}${SHIB_HANDLER_URL}/Login" index="1"/>
    </md:Extensions>
    <md:KeyDescriptor>
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:KeyName>dev-dotdeb</ds:KeyName>
        <ds:X509Data>
          <ds:X509SubjectName>CN=dev-dotdeb</ds:X509SubjectName>
          <ds:X509Certificate>MIIC5TCCAc2gAwIBAgIJAMTHl5c6BBC0MA0GCSqGSIb3DQEBBQUAMBUxEzARBgNV
BAMTCmRldi1kb3RkZWIwHhcNMTYwODA0MTMwNzQ3WhcNMjYwODAyMTMwNzQ3WjAV
MRMwEQYDVQQDEwpkZXYtZG90ZGViMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAuU5yPc7A8TmYSOkcA5WexnYdnbuPgIZV6pfCbWAlnsHM7tF2Y2nPM0x3
WIQD6iC2zNQrGa3vdjRDpFNZLZELqC4pCUj3kunLG6DYE5QL+8xuukJmt5OXksXn
wc+8kY4DAu3M/DnS0y6P4UGFMcgj8wZ6xZpzdSLRGqHx4a+dtuORy28sHEoChRqE
IbK2RdHvwIaOKttl1gjILgMKx7QgtBfoTk6iouC24ez9cpQ7zewDSQ9alzUbd7PP
xJg59pjlIZ1tL65TAMRXYy5sKUVONVx0u6znntpxWBfWC0vaB+LtJcPRNNfr3hx/
2rerB5wcgJsdqkI38BuiFF9iDyogSwIDAQABozgwNjAVBgNVHREEDjAMggpkZXYt
ZG90ZGViMB0GA1UdDgQWBBRj9FbPgOUNEIdgS1QtP6+ufIHx4DANBgkqhkiG9w0B
AQUFAAOCAQEAguatA2EtGF7ZrW+xJ7O7qymiLO90QKyIopCXdTeOs/Zcylo+0d8J
FKvbEFAOc3cfPwKfwvOg9yFzAFjpdIPqu+jPWgBG3EA/g0vR8SI31NpI4mPiSnXt
aUpWu42KFIMoHiELletPXan6jKHfHKl+SqTAY1ifVG7qLjSTrxihvn+zhrgKbai4
2c48v2xg1Q1rv11DKWB61y2xhhgOIYlbfsiKlbIznGVDyeBaEd0yF25NgByfLbx1
bcpYpzl5TERBGs27fizTDKUq3hszXzgq3iuo8vdXiFGBdJ0oZXvuTTlSJF0CPQ7K
2mj+QMjgmZXcmRJtE9dC7iGXgREs3v12HA==
</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
      <md:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#aes128-gcm"/>
      <md:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#aes192-gcm"/>
      <md:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#aes256-gcm"/>
      <md:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
      <md:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes192-cbc"/>
      <md:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc"/>
      <md:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#tripledes-cbc"/>
      <md:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#rsa-oaep"/>
      <md:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p"/>
    </md:KeyDescriptor>
    <md:ArtifactResolutionService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="${SHIB_HOSTNAME}${SHIB_HANDLER_URL}/Artifact/SOAP" index="1"/>
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="${SHIB_HOSTNAME}${SHIB_HANDLER_URL}/SLO/SOAP"/>
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="${SHIB_HOSTNAME}${SHIB_HANDLER_URL}/SLO/Redirect"/>
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="${SHIB_HOSTNAME}${SHIB_HANDLER_URL}/SLO/POST"/>
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="${SHIB_HOSTNAME}${SHIB_HANDLER_URL}/SLO/Artifact"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="${SHIB_HOSTNAME}${SHIB_HANDLER_URL}/SAML2/POST" index="1"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign" Location="${SHIB_HOSTNAME}${SHIB_HANDLER_URL}/SAML2/POST-SimpleSign" index="2"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="${SHIB_HOSTNAME}${SHIB_HANDLER_URL}/SAML2/Artifact" index="3"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:PAOS" Location="${SHIB_HOSTNAME}${SHIB_HANDLER_URL}/SAML2/ECP" index="4"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:1.0:profiles:browser-post" Location="${SHIB_HOSTNAME}${SHIB_HANDLER_URL}/SAML/POST" index="5"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:1.0:profiles:artifact-01" Location="${SHIB_HOSTNAME}${SHIB_HANDLER_URL}/SAML/Artifact" index="6"/>
  </md:SPSSODescriptor>

</md:EntityDescriptor>
EOF

  # activate debugging for shibboleth
sed -e 's/\(log4j\.rootCategory=\)[^,]\+/\1DEBUG/' -i /etc/shibboleth/console.logger

exec "$@"